DROP TABLE IF EXISTS "car";
CREATE TABLE "public"."car"
(
    "id"     bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "model"  character varying(255),
    "series" integer NOT NULL,
    CONSTRAINT "car_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

TRUNCATE "car";
INSERT INTO "car" ("id", "model", "series")
VALUES (1, 'BMV', 7),
       (2, 'Honda', 5),
       (3, 'Mazda', 4),
       (4, 'Jeep', 5);

DROP TABLE IF EXISTS "users";
CREATE TABLE "public"."users"
(
    "id"        bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email"     character varying(255),
    "firstname" character varying(255),
    "lastname"  character varying(255),
    "car_id"    bigint,
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

TRUNCATE "users";
INSERT INTO "users" ("id", "email", "firstname", "lastname", "car_id")
VALUES (1, 'user1@mail.ru', 'User1', 'Lastname1', 1),
       (2, 'user2@mail.ru', 'User2', 'Lastname2', 2),
       (3, 'user3@mail.ru', 'User3', 'Lastname3', 3),
       (4, 'user4@mail.ru', 'User4', 'Lastname4', 4);

ALTER TABLE ONLY "public"."users" ADD CONSTRAINT "fkhhpcps0or6nddhr80fq802jew" FOREIGN KEY (car_id) REFERENCES car(id) NOT DEFERRABLE;